package:
  name: enum
  version: !!str 0.4.4

source:
  fn: enum-0.4.4.tar.gz
  url: https://pypi.python.org/packages/source/e/enum/enum-0.4.4.tar.gz
  md5: ce75c7c3c86741175a84456cc5bd531e
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - enum = enum:main
    #
    # Would create an entry point called enum that calls enum.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - enum

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/enum/
  license: GNU General Public License (GPL) or Python Software Foundation License
  summary: u'Robust enumerated type support in Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
